# Paperboy first-run setup (Windows / PowerShell) — generates .env with unique secrets.
#
# PowerShell twin of scripts/setup.sh, because the README's "Super-simple setup
# (Windows)" walkthrough runs in PowerShell where a shell script won't work.
# See setup.sh for why generating these values is required rather than optional.
#
# Safe to re-run: an existing .env is never overwritten.
$ErrorActionPreference = 'Stop'

Set-Location (Join-Path $PSScriptRoot '..')

if (Test-Path '.env') {
  Write-Host "OK: .env already exists - leaving it untouched."
  Write-Host "    Delete it (or edit it by hand) if you want to regenerate secrets."
  exit 0
}

function New-RandomHex([int]$Bytes) {
  # RNGCryptoServiceProvider, NOT RandomNumberGenerator::Fill(Span<byte>): Fill is a
  # .NET Core 2.1+/.NET 5+ static, and the README tells beginners to open
  # "powershell" — which on Windows is PowerShell 5.1 on .NET Framework 4.x, where
  # that overload does not exist. With $ErrorActionPreference='Stop' the script would
  # abort before writing .env, and `docker compose up -d` would then inject the
  # placeholder secrets the API refuses to boot on: exactly the crash-loop this
  # script exists to prevent, on the one platform with a dedicated walkthrough.
  # RNGCryptoServiceProvider works on both 5.1 and 7+.
  $buffer = New-Object byte[] $Bytes
  $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
  try { $rng.GetBytes($buffer) } finally { $rng.Dispose() }
  ($buffer | ForEach-Object { $_.ToString('x2') }) -join ''
}

$adminEmail = if ($env:SEED_ADMIN_EMAIL) { $env:SEED_ADMIN_EMAIL } else { 'admin@paperboy.test' }
$adminPassword = New-RandomHex 12

@"
# Generated by scripts/setup.ps1 - unique to this install. Keep it out of git.
# Regenerate by deleting this file and re-running the script.

# --- Secrets (generated) ---------------------------------------------------
SESSION_SECRET=$(New-RandomHex 32)
CSRF_SECRET=$(New-RandomHex 32)
# Encrypts TOTP secrets and stored AI/stock keys at rest. Changing it later
# makes existing 2FA enrolments and stored keys undecryptable - pin it.
MFA_SECRET=$(New-RandomHex 32)
PREVIEW_SECRET=$(New-RandomHex 24)

# --- Delivery API keys (generated) ----------------------------------------
PAPERBOY_PUBLIC_KEY=pk_live_$(New-RandomHex 16)
PAPERBOY_PREVIEW_KEY=prv_$(New-RandomHex 16)

# --- First admin login ----------------------------------------------------
SEED_ADMIN_EMAIL=$adminEmail
SEED_ADMIN_PASSWORD=$adminPassword

# --- Localhost defaults ---------------------------------------------------
# Cookies can't be Secure over plain http://localhost, so the login would be
# dropped. Both of these MUST be flipped (COOKIE_SECURE=true, and drop
# ALLOW_INSECURE_COOKIES) before exposing this over anything but localhost.
COOKIE_SECURE=false
ALLOW_INSECURE_COOKIES=true
CORS_ORIGIN=http://localhost:8090
"@ | Set-Content -Path '.env' -Encoding ascii

Write-Host "OK: wrote .env with generated secrets."
Write-Host ""
Write-Host "  Admin login:  $adminEmail"
Write-Host "  Password:     $adminPassword"
Write-Host ""
Write-Host "  ^ Save that password now - it is not stored anywhere else."
Write-Host ""
Write-Host "Next:  docker compose up -d     then open http://localhost:8090"
