#!/usr/bin/env sh
# Paperboy first-run setup — generates .env with unique secrets.
#
# Why this exists: docker-compose ships `${SESSION_SECRET:-prod-…-please-override…}`
# style defaults, and the API refuses to boot on a shipped placeholder (correctly —
# they are committed in a public repo). So a clean `docker compose up -d` used to
# crash-loop the api, and because web/admin wait on `service_healthy` the whole
# stack never came up. Generating real values here keeps the guard AND makes the
# documented quickstart work.
#
# Safe to re-run: an existing .env is never overwritten.
set -eu

cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo "✓ .env already exists — leaving it untouched."
  echo "  Delete it (or edit it by hand) if you want to regenerate secrets."
  exit 0
fi

# openssl is present in git-bash, macOS and every mainstream Linux; fall back to
# /dev/urandom so this works on a minimal container too.
rand() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$1"
  else
    head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

ADMIN_EMAIL="${SEED_ADMIN_EMAIL:-admin@paperboy.test}"
ADMIN_PASSWORD="$(rand 12)"

cat > .env <<EOF
# Generated by scripts/setup.sh — unique to this install. Keep it out of git.
# Regenerate by deleting this file and re-running the script.

# --- Secrets (generated) ---------------------------------------------------
SESSION_SECRET=$(rand 32)
CSRF_SECRET=$(rand 32)
# Encrypts TOTP secrets and stored AI/stock keys at rest. Changing it later
# makes existing 2FA enrolments and stored keys undecryptable — pin it.
MFA_SECRET=$(rand 32)
PREVIEW_SECRET=$(rand 24)

# --- Delivery API keys (generated) ----------------------------------------
PAPERBOY_PUBLIC_KEY=pk_live_$(rand 16)
PAPERBOY_PREVIEW_KEY=prv_$(rand 16)

# --- First admin login ----------------------------------------------------
SEED_ADMIN_EMAIL=$ADMIN_EMAIL
SEED_ADMIN_PASSWORD=$ADMIN_PASSWORD

# --- Localhost defaults ---------------------------------------------------
# Cookies can't be Secure over plain http://localhost, so the login would be
# dropped. Both of these MUST be flipped (COOKIE_SECURE=true, and drop
# ALLOW_INSECURE_COOKIES) before exposing this over anything but localhost.
COOKIE_SECURE=false
ALLOW_INSECURE_COOKIES=true
CORS_ORIGIN=http://localhost:8090
EOF

chmod 600 .env

echo "✓ Wrote .env with generated secrets (chmod 600)."
echo
echo "  Admin login:  $ADMIN_EMAIL"
echo "  Password:     $ADMIN_PASSWORD"
echo
echo "  ^ Save that password now — it is not stored anywhere else."
echo
echo "Next:  docker compose up -d     then open http://localhost:8090"
