import { publicFileResponse } from "../lib/public-file";

/** robots.txt is generated by the CMS (Settings → Site → Public files). */
export const dynamic = "force-dynamic"; // never prerendered: the CMS isn't reachable at build time

export async function GET(): Promise<Response> {
  return publicFileResponse("robots.txt");
}
