import { publicFileResponse } from "../lib/public-file";

/** robots.txt is generated by the CMS (Settings → Site → Public files). */
export async function GET(): Promise<Response> {
  return publicFileResponse("robots.txt");
}
